language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
matrix:
    allow_failures:
        - python: "2.6"
        - python: "3.2"
        - python: "3.3"
        - python: "pypy"
install:
    - uname -a
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl protobuf-compiler libprotobuf-dev libncurses5 libc6 wget
    - sudo wget https://raw.github.com/alavrik/piqi-binary/master/Linux-x86_64/piqi -O /usr/bin/piqi
    - sudo chmod +x /usr/bin/piqi
    - pip install --upgrade https://bitbucket.org/logilab/astroid/get/5ed6266cab78.zip
    - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]];
            then pip install -r requirements-dev-py3.txt;
            else pip install -r requirements-dev-py2.txt;
        fi;
    - python setup.py build
    - python setup.py install
script: make test && make check
