language: python
python:
    - "2.6"
    - "2.7"
install:
    - uname -a
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl protobuf-compiler libprotobuf-dev libncurses5 libc6
    - sudo sh -c "curl -k https://raw.github.com/alavrik/piqi-erlang/master/priv/bin-Linux-x86_64/piqi > /usr/bin/piqi"
    - sudo sh -c "curl -k https://raw.github.com/alavrik/piqi-erlang/master/priv/bin-Linux-x86_64/piqic > /usr/bin/piqic"
    - sudo chmod +x /usr/bin/piqi /usr/bin/piqic
    - pip install --upgrade -r requirements-dev.txt
script: make test && make check
